version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # You can change this to your preferred Java version
    commands:
      - echo Installing Maven
      - apt-get update -y
      - apt-get install -y maven

  pre_build:
    commands:
      - echo Running pre_build commands
      - mvn -version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar # Adjust this depending on your project structure and output

cache:
  paths:
    - '/root/.m2/**/*'
