version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17 # Using Java Corretto 17
    commands:
      - echo Installing Maven
      - yum update -y        # Updated to use yum
      - yum install -y maven # Updated to use yum

  pre_build:
    commands:
      - echo Running pre_build commands
      - mvn -version

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar # Specify the artifacts to be output

cache:
  paths:
    - '/root/.m2/**/*'
